vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        post_main_image:
            uri_prefix: /images/post/main
            upload_destination: '%kernel.project_dir%/public/images/post/main'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
